name: Website

on: [workflow_dispatch, push]

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🔑 Configure SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: 🚀 Upload
        run: rsync --archive --delete --exclude admin --stats -e 'ssh -p 18765' 'src/' ${{ secrets.REMOTE_DEST }}
      - name: 🧹 Purge Cache
        run: curl https://maui.graphics/admin/purge/
